<?php
session_start();
unset($_SESSION['id_anggota']);
unset($_SESSION['nama_lengkap']);
unset($_SESSION['login']);
unset($_SESSION['loginadmin']); 
unset($_SESSION['id_admin']);
session_destroy();
header('location:../');
?>